/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarWishDto } from '../../models/car-wish-dto';
import { UpdateCarWishDto } from '../../models/update-car-wish-dto';

export interface CarWishControllerUpdateWish$Params {
  id: string;
      body: UpdateCarWishDto
}

export function carWishControllerUpdateWish(http: HttpClient, rootUrl: string, params: CarWishControllerUpdateWish$Params, context?: HttpContext): Observable<StrictHttpResponse<CarWishDto>> {
  const rb = new RequestBuilder(rootUrl, carWishControllerUpdateWish.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarWishDto>;
    })
  );
}

carWishControllerUpdateWish.PATH = '/api/car-wish/{id}';
