/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarWishlistDto } from '../../models/car-wishlist-dto';

export interface CarWishControllerGetWishlist$Params {
  carId: string;
}

export function carWishControllerGetWishlist(http: HttpClient, rootUrl: string, params: CarWishControllerGetWishlist$Params, context?: HttpContext): Observable<StrictHttpResponse<CarWishlistDto>> {
  const rb = new RequestBuilder(rootUrl, carWishControllerGetWishlist.PATH, 'get');
  if (params) {
    rb.path('carId', params.carId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarWishlistDto>;
    })
  );
}

carWishControllerGetWishlist.PATH = '/api/car-wish/car/{carId}';
