/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarWishDto } from '../../models/car-wish-dto';
import { ReorderCarWishesDto } from '../../models/reorder-car-wishes-dto';

export interface CarWishControllerReorderWishes$Params {
  carId: string;
      body: ReorderCarWishesDto
}

export function carWishControllerReorderWishes(http: HttpClient, rootUrl: string, params: CarWishControllerReorderWishes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CarWishDto>>> {
  const rb = new RequestBuilder(rootUrl, carWishControllerReorderWishes.PATH, 'put');
  if (params) {
    rb.path('carId', params.carId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CarWishDto>>;
    })
  );
}

carWishControllerReorderWishes.PATH = '/api/car-wish/car/{carId}/reorder';
