/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarWishDto } from '../../models/car-wish-dto';

export interface CarWishControllerDeleteWish$Params {
  id: string;
}

export function carWishControllerDeleteWish(http: HttpClient, rootUrl: string, params: CarWishControllerDeleteWish$Params, context?: HttpContext): Observable<StrictHttpResponse<CarWishDto>> {
  const rb = new RequestBuilder(rootUrl, carWishControllerDeleteWish.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarWishDto>;
    })
  );
}

carWishControllerDeleteWish.PATH = '/api/car-wish/{id}';
