/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarWishlistDto } from '../../models/car-wishlist-dto';
import { UpdateWishlistBudgetDto } from '../../models/update-wishlist-budget-dto';

export interface CarWishControllerSetBudget$Params {
  carId: string;
      body: UpdateWishlistBudgetDto
}

export function carWishControllerSetBudget(http: HttpClient, rootUrl: string, params: CarWishControllerSetBudget$Params, context?: HttpContext): Observable<StrictHttpResponse<CarWishlistDto>> {
  const rb = new RequestBuilder(rootUrl, carWishControllerSetBudget.PATH, 'put');
  if (params) {
    rb.path('carId', params.carId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarWishlistDto>;
    })
  );
}

carWishControllerSetBudget.PATH = '/api/car-wish/car/{carId}/budget';
