/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarWishDto } from '../../models/car-wish-dto';
import { CreateCarWishDto } from '../../models/create-car-wish-dto';

export interface CarWishControllerCreateWish$Params {
      body: CreateCarWishDto
}

export function carWishControllerCreateWish(http: HttpClient, rootUrl: string, params: CarWishControllerCreateWish$Params, context?: HttpContext): Observable<StrictHttpResponse<CarWishDto>> {
  const rb = new RequestBuilder(rootUrl, carWishControllerCreateWish.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarWishDto>;
    })
  );
}

carWishControllerCreateWish.PATH = '/api/car-wish';
