openapi: "3.0.0"
paths:
  /api/car:
    post:
      operationId: "CarController_createCar"
      summary: "Create a new car"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddCarDto"
      responses:
        201:
          description: "The car has been successfully created."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarDto"
        403:
          description: "Forbidden."
      tags:
        - "car"
      security:
        - cookie: []
    put:
      operationId: "CarController_updateCar"
      summary: "Update a car"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCarDto"
      responses:
        200:
          description: "The car has been successfully updated."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarDto"
        404:
          description: "Car not found."
      tags:
        - "car"
      security:
        - cookie: []
    get:
      operationId: "CarController_getAllCars"
      summary: "Get all cars"
      parameters: []
      responses:
        200:
          description: "Return list of cars."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CarDto"
      tags:
        - "car"
      security:
        - cookie: []
  /api/car/{id}:
    get:
      operationId: "CarController_getCar"
      summary: "Get car by ID"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Return car details."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarDto"
        404:
          description: "Car not found."
      tags:
        - "car"
      security:
        - cookie: []
    delete:
      operationId: "CarController_deleteCar"
      summary: "Delete a car"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "The car has been successfully deleted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarDto"
        404:
          description: "Car not found."
      tags:
        - "car"
      security:
        - cookie: []
  /api/car/user/{userId}:
    get:
      operationId: "CarController_getCarsByUser"
      summary: "Get all cars for a specific user"
      parameters:
        - name: "user-id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Return list of cars."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CarDto"
      tags:
        - "car"
      security:
        - cookie: []
  /api/maintenance-record:
    post:
      operationId: "MaintenanceRecordController_createMaintenanceRecord"
      summary: "Create a new maintenance record"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMaintenanceRecordDto"
      responses:
        201:
          description: "The maintenance record has been successfully created."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceRecordDto"
      tags:
        - "maintenance-record"
      security:
        - bearer: []
  /api/maintenance-record/{id}:
    get:
      operationId: "MaintenanceRecordController_getMaintenanceRecord"
      summary: "Get maintenance record by ID"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Return maintenance record details."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceRecordDto"
        404:
          description: "Maintenance record not found."
      tags:
        - "maintenance-record"
      security:
        - bearer: []
    put:
      operationId: "MaintenanceRecordController_updateMaintenanceRecord"
      summary: "Update a maintenance record"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMaintenanceRecordDto"
      responses:
        200:
          description: "The maintenance record has been successfully updated."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceRecordDto"
        404:
          description: "Maintenance record not found."
      tags:
        - "maintenance-record"
      security:
        - bearer: []
    delete:
      operationId: "MaintenanceRecordController_deleteMaintenanceRecord"
      summary: "Delete a maintenance record"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "The maintenance record has been successfully deleted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceRecordDto"
        404:
          description: "Maintenance record not found."
      tags:
        - "maintenance-record"
      security:
        - bearer: []
  /api/maintenance-record/car/{carId}:
    get:
      operationId: "MaintenanceRecordController_getMaintenanceRecordsByCarId"
      summary: "Get all maintenance records for a specific car"
      parameters:
        - name: "carId"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Return list of maintenance records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/MaintenanceRecordDto"
        404:
          description: "Maintenance records not found."
      tags:
        - "maintenance-record"
      security:
        - bearer: []
  /api/document:
    post:
      operationId: "DocumentController_createDocument"
      summary: "Create a new document"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDocumentDto"
      responses:
        201:
          description: "The document has been successfully created."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentDto"
        403:
          description: "Forbidden."
      tags:
        - "document"
  /api/document/{id}:
    get:
      operationId: "DocumentController_getDocument"
      summary: "Get document by ID"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Return document details."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentDto"
        404:
          description: "Document not found."
      tags:
        - "document"
    put:
      operationId: "DocumentController_updateDocument"
      summary: "Update a document"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDocumentDto"
      responses:
        200:
          description: "The document has been successfully updated."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentDto"
        404:
          description: "Document not found."
      tags:
        - "document"
    delete:
      operationId: "DocumentController_deleteDocument"
      summary: "Delete a document"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "The document has been successfully deleted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentDto"
        404:
          description: "Document not found."
      tags:
        - "document"
  /api/document/car/{carId}:
    get:
      operationId: "DocumentController_getDocumentsByCarId"
      summary: "Get all documents for a specific car"
      parameters:
        - name: "carId"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Return list of documents."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DocumentDto"
        404:
          description: "Documents not found."
      tags:
        - "document"
  /api/auth/google:
    get:
      operationId: "AuthController_login"
      summary: "Login user and set access token in HTTP-only cookie"
      description: "Authenticates a user via Google and stores the access token in a secure HTTP-only cookie."
      parameters: []
      responses:
        200:
          description: "User successfully logged in, access token set in cookie."
        401:
          description: "Unauthorized access."
      tags:
        - "auth"
  /api/auth/google/redirect:
    get:
      operationId: "AuthController_googleAuthRedirect"
      summary: "Handle Google OAuth redirection"
      description: "Processes the Google authentication response and sets access token in HTTP-only cookie."
      parameters: []
      responses:
        302:
          description: "User is authenticated and redirected to the frontend."
        401:
          description: "Unauthorized - Google authentication failed."
      tags:
        - "auth"
  /api/auth/refresh:
    post:
      operationId: "AuthController_refreshAccessToken"
      summary: "Refresh access token using refresh token"
      description: "Generates a new access token if the refresh token is valid."
      parameters: []
      responses:
        200:
          description: "New access token generated successfully."
        401:
          description: "Unauthorized - Refresh token missing or invalid."
      tags:
        - "auth"
  /api/auth/me:
    get:
      operationId: "AuthController_getProfile"
      summary: "Get user details from access token"
      description: "Validates the access token stored in HTTP-only cookie and returns user information."
      parameters: []
      responses:
        200:
          description: "User details successfully retrieved."
        401:
          description: "Unauthorized - Invalid or missing access token."
      tags:
        - "auth"
  /api/auth/logout:
    post:
      operationId: "AuthController_logout"
      summary: "Logout user and clear authentication tokens"
      description: "Removes access token from cookies and invalidates refresh token in the database."
      parameters: []
      responses:
        200:
          description: "User successfully logged out."
        401:
          description: "Unauthorized - No active session found."
      tags:
        - "auth"
info:
  title: "History Auto Utility API"
  description: "API documentation for History Auto Utility"
  version: "1.0"
  contact: {}
tags: []
servers:
  - url: "http://localhost:3000"
    description: "development"
components:
  securitySchemes:
    bearer:
      scheme: "bearer"
      bearerFormat: "JWT"
      type: "http"
    cookie:
      type: "apiKey"
      in: "cookie"
      name: "access_token"
  schemas:
    AddCarDto:
      type: "object"
      properties:
        id:
          type: "number"
          example: "6"
        vin:
          type: "string"
          example: "WBAHE21060GE64612"
        make:
          type: "string"
          example: "BMW"
        model:
          type: "string"
          example: "530iA"
        year:
          type: "number"
          example: 1992
        license_plate:
          type: "string"
          example: "B13HAU"
        current_mileage:
          type: "number"
          example: 380000
        image:
          type: "string"
          example: "base64/someImageHere"
      required:
        - "id"
        - "vin"
        - "make"
        - "model"
        - "year"
        - "license_plate"
        - "current_mileage"
        - "image"
    CarDto:
      type: "object"
      properties:
        id:
          type: "number"
          example: 1
        user_id:
          type: "number"
          example: 123
        vin:
          type: "string"
          example: "1HGCM82633A123456"
        make:
          type: "string"
          example: "BMW"
        model:
          type: "string"
          example: "530iA"
        year:
          type: "number"
          example: 1992
        license_plate:
          type: "string"
          example: "B13HAU"
        current_mileage:
          type: "number"
          example: 380000
        image:
          type: "string"
          example: "base64/someImageHere"
      required:
        - "id"
        - "user_id"
        - "vin"
        - "make"
        - "model"
        - "year"
        - "license_plate"
        - "current_mileage"
        - "image"
    UpdateCarDto:
      type: "object"
      properties: {}
    CreateMaintenanceRecordDto:
      type: "object"
      properties:
        car_id:
          type: "number"
          example: "123"
        service_date:
          format: "date-time"
          type: "string"
          example: "2023-01-01T00:00:00.000Z"
        mileage:
          type: "number"
          example: "380000"
        description:
          type: "string"
          example: "Oil 10W40, air filter MANN"
        service_type:
          type: "string"
          example: "MAINTENANCE"
          enum:
            - "REPAIR"
            - "MAINTENANCE"
            - "IMPROVEMENT"
        service_category:
          type: "string"
          example: "OIL_CHANGE"
          enum:
            - "OIL_CHANGE"
            - "BRAKE_SERVICE"
            - "TRANSMISSION_SERVICE"
            - "TIRE_SERVICE"
            - "OTHER"
        cost:
          type: "number"
          example: "Insurance"
        expiry_date:
          format: "date-time"
          type: "string"
          example: "Insurance"
      required:
        - "car_id"
        - "service_date"
        - "mileage"
        - "description"
        - "service_type"
        - "service_category"
        - "cost"
        - "expiry_date"
    MaintenanceRecordDto:
      type: "object"
      properties:
        id:
          type: "number"
          example: "123"
        car_id:
          type: "number"
          example: "123"
        service_date:
          format: "date-time"
          type: "string"
          example: "2023-01-01T00:00:00.000Z"
        mileage:
          type: "number"
          example: "380000"
        description:
          type: "string"
          example: "Oil 10W40, air filter MANN"
        service_type:
          type: "string"
          example: "MAINTENANCE"
          enum:
            - "REPAIR"
            - "MAINTENANCE"
            - "IMPROVEMENT"
        service_category:
          type: "string"
          example: "OIL_CHANGE"
          enum:
            - "OIL_CHANGE"
            - "BRAKE_SERVICE"
            - "TRANSMISSION_SERVICE"
            - "TIRE_SERVICE"
            - "OTHER"
        cost:
          type: "number"
          example: "Insurance"
        expiry_date:
          format: "date-time"
          type: "string"
          example: "Insurance"
      required:
        - "id"
        - "car_id"
        - "service_date"
        - "mileage"
        - "description"
        - "service_type"
        - "service_category"
        - "cost"
        - "expiry_date"
    UpdateMaintenanceRecordDto:
      type: "object"
      properties: {}
    CreateDocumentDto:
      type: "object"
      properties:
        document_type:
          type: "string"
          example: "Insurance"
        issue_date:
          format: "date-time"
          type: "string"
          example: "2023-01-01T00:00:00.000Z"
        expiry_date:
          format: "date-time"
          type: "string"
          example: "2024-01-01T00:00:00.000Z"
        car_id:
          type: "number"
          example: 1
      required:
        - "document_type"
        - "issue_date"
        - "expiry_date"
        - "car_id"
    DocumentDto:
      type: "object"
      properties:
        id:
          type: "number"
          example: 1
        document_type:
          type: "string"
          example: "Insurance"
        issue_date:
          format: "date-time"
          type: "string"
          example: "2023-01-01T00:00:00.000Z"
        expiry_date:
          format: "date-time"
          type: "string"
          example: "2024-01-01T00:00:00.000Z"
        car_id:
          type: "number"
          example: 1
      required:
        - "id"
        - "document_type"
        - "issue_date"
        - "expiry_date"
        - "car_id"
    UpdateDocumentDto:
      type: "object"
      properties: {}
