import { BlogEntry, MockCarForBlog } from '@hau/features/blog/models/blog.model';

// ── Cars available for Vehicle Journal ───────────────────────────────
export const MOCK_CARS_FOR_BLOG: MockCarForBlog[] = [
  {
    id: 1,
    name: 'BMW 520i',
    plate: 'IS49WAU',
    km: 184200,
    gradient: 'linear-gradient(160deg, #1a1a2e 0%, #2d3561 100%)',
  },
  {
    id: 2,
    name: 'BMW 318iA',
    plate: 'BV31HAU',
    km: 168300,
    gradient: 'linear-gradient(160deg, #232526 0%, #414345 100%)',
  },
  {
    id: 3,
    name: 'BMW 525iA',
    plate: 'B33HAU',
    km: 198750,
    gradient: 'linear-gradient(160deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
  },
  {
    id: 4,
    name: 'Ford Ranger',
    plate: 'RO 22 BGF',
    km: 72400,
    gradient: 'linear-gradient(160deg, #1b4332 0%, #2d6a4f 100%)',
  },
];

// ── Blog entries ─────────────────────────────────────────────────────
export const MOCK_BLOG_ENTRIES: BlogEntry[] = [
  // Personal entries
  {
    id: 1,
    category: 'personal',
    title: 'Weekend escape in the mountains',
    date: '2026-05-12',
    tags: [
      { label: 'Travel', color: 'blue' },
      { label: 'Adventure', color: 'purple' },
    ],
    content: 'Spent an amazing weekend up in the mountains. The views were breathtaking and the roads were perfect for a drive.\n\nStopped at a small village for some traditional food and met some great people.\n\nCan\'t wait for the next trip!',
    images: [],
    coverGradient: 'linear-gradient(160deg, #2980B9 0%, #6DD5FA 55%, #a8edea 100%)',
    isPinned: true,
    createdAt: '2026-05-12T09:00:00Z',
  },
  {
    id: 2,
    category: 'personal',
    title: 'Camping under the stars',
    date: '2026-04-28',
    tags: [
      { label: 'Personal', color: 'green' },
      { label: 'Memories', color: 'orange' },
    ],
    content: 'Decided last minute to go camping. Set up the tent, lit a fire and spent the whole night looking at the stars.\n\nNo phone signal, no distractions. Just the sound of the forest and a crackling fire.\n\nDefinitely doing this more often.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #f83600 0%, #f9d423 100%)',
    isPinned: true,
    createdAt: '2026-04-28T20:00:00Z',
  },
  {
    id: 3,
    category: 'personal',
    title: 'Road trip to Transfăgărășan',
    date: '2026-05-10',
    tags: [{ label: 'Travel', color: 'blue' }],
    content: 'The Transfăgărășan is truly one of the most spectacular roads in the world. Started from Curtea de Argeș at dawn and reached the top just as the fog was lifting.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    isPinned: false,
    createdAt: '2026-05-10T07:30:00Z',
  },
  {
    id: 4,
    category: 'personal',
    title: 'New hiking trail discovered',
    date: '2026-05-02',
    tags: [
      { label: 'Hiking', color: 'green' },
      { label: 'Adventure', color: 'purple' },
    ],
    content: 'Found a hidden trail behind the old monastery. It takes about 3 hours to complete and the views from the ridge are stunning.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #134E5E 0%, #71B280 100%)',
    isPinned: false,
    createdAt: '2026-05-02T10:00:00Z',
  },
  {
    id: 5,
    category: 'personal',
    title: 'Photography day',
    date: '2026-04-21',
    tags: [{ label: 'Photography', color: 'purple' }],
    content: 'Spent the entire day with the camera, shooting around the city. Golden hour light was spectacular.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #232526 0%, #414345 100%)',
    isPinned: false,
    createdAt: '2026-04-21T15:00:00Z',
  },
  {
    id: 6,
    category: 'personal',
    title: 'Sunset by the lake',
    date: '2026-04-15',
    tags: [{ label: 'Personal', color: 'green' }],
    content: 'Drove out to the lake after work. The sunset was incredible — orange and pink reflections on the water.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #1CB5E0 0%, #000046 100%)',
    isPinned: false,
    createdAt: '2026-04-15T19:00:00Z',
  },

  // Vehicle Journal — BMW 520i (id=1)
  {
    id: 7,
    category: 'vehicle',
    title: 'Oil service completed',
    date: '2026-03-12',
    tags: [
      { label: 'Service visit', color: 'teal' },
      { label: 'Oil change', color: 'blue' },
      { label: 'Liqui Moly', color: 'orange' },
    ],
    content: 'Changed engine oil and filter with Liqui Moly 5W-40. Checked all fluids and tire pressure.\n\nCar runs smoother and quieter now.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    isPinned: false,
    carId: 1,
    carName: 'BMW 520i',
    vehicleCategory: 'service_visit',
    km: 184300,
    price: 450,
    createdAt: '2026-03-12T11:00:00Z',
  },
  {
    id: 8,
    category: 'vehicle',
    title: 'Trip to Sibiu',
    date: '2026-03-05',
    tags: [
      { label: 'Road trip', color: 'blue' },
      { label: 'Sibiu', color: 'purple' },
      { label: 'A1', color: 'teal' },
      { label: 'Weekend', color: 'green' },
    ],
    content: 'Weekend road trip from Cluj to Sibiu via the A1 highway. 280 km round trip, amazing scenery through the Apuseni.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #134E5E 0%, #71B280 100%)',
    isPinned: false,
    carId: 1,
    carName: 'BMW 520i',
    vehicleCategory: 'trip',
    km: 183650,
    createdAt: '2026-03-05T08:00:00Z',
  },
  {
    id: 9,
    category: 'vehicle',
    title: 'Front brake pads replaced',
    date: '2026-03-01',
    tags: [
      { label: 'Repair', color: 'orange' },
      { label: 'Brakes', color: 'pink' },
      { label: 'Pagid', color: 'purple' },
    ],
    content: 'Front brake pads replaced with Pagid RS 4-2. Rotors were still in good shape. Bedding-in done over 50 km.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #c31432 0%, #240b36 100%)',
    isPinned: false,
    carId: 1,
    carName: 'BMW 520i',
    vehicleCategory: 'repair',
    km: 183100,
    price: 620,
    createdAt: '2026-03-01T14:00:00Z',
  },
  {
    id: 10,
    category: 'vehicle',
    title: 'Weekend mountain drive',
    date: '2026-02-22',
    tags: [
      { label: 'Trip', color: 'blue' },
      { label: 'Transfăgărășan', color: 'teal' },
      { label: 'Mountains', color: 'green' },
    ],
    content: 'Drove up to Transfăgărășan — still partially open in February. Incredible views, light traffic.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #005C97 0%, #363795 100%)',
    isPinned: false,
    carId: 1,
    carName: 'BMW 520i',
    vehicleCategory: 'trip',
    km: 182400,
    createdAt: '2026-02-22T07:00:00Z',
  },

  // Vehicle Journal — BMW 318iA (id=2)
  {
    id: 11,
    category: 'vehicle',
    title: 'Annual ITP — passed',
    date: '2026-04-10',
    tags: [
      { label: 'Inspection', color: 'teal' },
      { label: 'ITP', color: 'blue' },
    ],
    content: 'Annual technical inspection passed with no issues. Next due April 2027.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #43cea2 0%, #185a9d 100%)',
    isPinned: false,
    carId: 2,
    carName: 'BMW 318iA',
    vehicleCategory: 'inspection',
    km: 168300,
    price: 120,
    createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 12,
    category: 'vehicle',
    title: 'RCA renewed — Allianz',
    date: '2026-03-28',
    tags: [
      { label: 'Upgrade', color: 'purple' },
      { label: 'Insurance', color: 'teal' },
    ],
    content: 'Renewed RCA insurance for another year with Allianz. Better coverage than last year at a lower price.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #373B44 0%, #4286f4 100%)',
    isPinned: false,
    carId: 2,
    carName: 'BMW 318iA',
    vehicleCategory: 'upgrade',
    km: 168100,
    price: 890,
    createdAt: '2026-03-28T15:00:00Z',
  },

  // Vehicle Journal — BMW 525iA (id=3)
  {
    id: 13,
    category: 'vehicle',
    title: 'Gearbox fluid change',
    date: '2026-04-15',
    tags: [
      { label: 'Repair', color: 'orange' },
      { label: 'Gearbox', color: 'purple' },
    ],
    content: 'Automatic gearbox fluid replaced with BMW Dexron VI approved fluid. Shifts are noticeably smoother.',
    images: [],
    coverGradient: 'linear-gradient(135deg, #0f2027 0%, #203a43 100%)',
    isPinned: false,
    carId: 3,
    carName: 'BMW 525iA',
    vehicleCategory: 'repair',
    km: 198750,
    price: 380,
    createdAt: '2026-04-15T12:00:00Z',
  },
];
