/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarNoteDto } from '../../models/car-note-dto';

export interface CarNoteControllerDeleteCarNote$Params {
  id: string;
}

export function carNoteControllerDeleteCarNote(http: HttpClient, rootUrl: string, params: CarNoteControllerDeleteCarNote$Params, context?: HttpContext): Observable<StrictHttpResponse<CarNoteDto>> {
  const rb = new RequestBuilder(rootUrl, carNoteControllerDeleteCarNote.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarNoteDto>;
    })
  );
}

carNoteControllerDeleteCarNote.PATH = '/api/car-note/{id}';
