/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarNoteDto } from '../../models/car-note-dto';
import { CreateCarNoteDto } from '../../models/create-car-note-dto';

export interface CarNoteControllerCreateCarNote$Params {
      body: CreateCarNoteDto
}

export function carNoteControllerCreateCarNote(http: HttpClient, rootUrl: string, params: CarNoteControllerCreateCarNote$Params, context?: HttpContext): Observable<StrictHttpResponse<CarNoteDto>> {
  const rb = new RequestBuilder(rootUrl, carNoteControllerCreateCarNote.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarNoteDto>;
    })
  );
}

carNoteControllerCreateCarNote.PATH = '/api/car-note';
