/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddCarDto {
  id?: number;
  make: string;
  model: string;
  variant?: string;
  license_plate: string;
  vin?: string;
  year: number;
  fuel_type?: 'PETROL' | 'DIESEL' | 'HYBRID' | 'PLUGIN_HYBRID' | 'ELECTRIC' | 'LPG';
  transmission?: 'MANUAL' | 'AUTOMATIC' | 'SEMI_AUTOMATIC';
  engine?: string;
  color?: string;
  current_mileage: number;
  ownership_start_date?: string;
  rca_expiry_date?: string;
  itp_expiry_date?: string;
  rov_expiry_date?: string;
  last_oil_service_date?: string;
  last_oil_service_mileage?: number;
}
