/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type BlogCategoryApi = 'PERSONAL' | 'VEHICLE';

export type BlogStatusApi = 'DRAFT' | 'PUBLISHED';

export type VehicleEntryCategoryApi =
  | 'REPAIR'
  | 'SERVICE_VISIT'
  | 'TRIP'
  | 'FUEL'
  | 'UPGRADE'
  | 'INSPECTION'
  | 'BREAKDOWN'
  | 'OTHER';

export interface BlogTagDto {
  id: number;
  label: string;
  color: string;
}

export interface BlogImageDto {
  id: number;
  url: string;
}

export interface BlogEntryDto {
  id: number;
  user_id: number;
  category: BlogCategoryApi;
  title: string;
  slug: string | null;
  excerpt: string | null;
  date: string;
  content: string;
  content_json: Record<string, unknown> | null;
  status: BlogStatusApi;
  published_at: string | null;
  is_pinned: boolean;
  cover_gradient: string | null;
  cover_image_url: string | null;
  car_id: number | null;
  car_name: string | null;
  vehicle_category: VehicleEntryCategoryApi | null;
  km: number | null;
  price: number | null;
  tags: BlogTagDto[];
  images: BlogImageDto[];
  created_at: string;
  updated_at: string;
}

export interface VehicleCategoryDto {
  value: VehicleEntryCategoryApi;
  label: string;
}
