/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarNoteChecklistItemDto } from '../models/car-note-checklist-item-dto';
export interface CarNoteDto {
  car_id: number;
  color?: string | null;
  content: string;
  created_at: string;

  /**
   * Legacy single group, superseded by `labels`.
   */
  group_name?: string | null;
  id: number;
  is_checklist: boolean;
  checked_in_place: boolean;
  items: Array<CarNoteChecklistItemDto>;
  labels: Array<string>;
  title: string;
  updated_at: string;
}
