/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceType } from './maintenance-record-dto';

export type CarWishStatus = 'ACTIVE' | 'DONE' | 'DROPPED';

export interface CarWishDto {
  car_id: number;
  created_at: string;
  done_at?: string | null;
  estimated_cost?: number | null;
  id: number;
  notes?: string | null;
  position: number;
  service_type?: ServiceType | null;
  status: CarWishStatus;
  title: string;
  updated_at: string;
}
