/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarPhotoDto {
  id: number;
  url: string;
  is_default: boolean;
}

export interface CarDto {
  id: number;
  user_id: number;
  vin?: string | null;
  make: string;
  model: string;
  variant?: string | null;
  year: number;
  license_plate: string;
  fuel_type?: 'PETROL' | 'DIESEL' | 'HYBRID' | 'PLUGIN_HYBRID' | 'ELECTRIC' | 'LPG' | null;
  transmission?: 'MANUAL' | 'AUTOMATIC' | 'SEMI_AUTOMATIC' | null;
  engine?: string | null;
  color?: string | null;
  current_mileage: number;
  ownership_start_date?: string | null;
  rca_expiry_date?: string | null;
  itp_expiry_date?: string | null;
  rov_expiry_date?: string | null;
  last_oil_service_date?: string | null;
  last_oil_service_mileage?: number | null;
  photos: CarPhotoDto[];
}
