/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarNoteDto {
  car_id: number;
  content: string;
  created_at: string;
  group_name?: string | null;
  id: number;
  title: string;
  updated_at: string;
}
