/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarWishDto } from './car-wish-dto';

export interface CarWishlistDto {
  budget?: number | null;
  items: Array<CarWishDto>;
}
