/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlogCategoryApi, BlogStatusApi, VehicleEntryCategoryApi } from './blog-entry-dto';

export interface CreateBlogTagDto {
  label: string;
  color: string;
}

export interface CreateBlogEntryDto {
  category: BlogCategoryApi;
  title: string;
  slug?: string;
  excerpt?: string;
  date: string;
  content?: string;
  content_json?: Record<string, unknown>;
  status?: BlogStatusApi;
  is_pinned?: boolean;
  cover_gradient?: string;
  cover_image_url?: string;
  car_id?: number;
  vehicle_category?: VehicleEntryCategoryApi;
  km?: number;
  price?: number;
  tags?: CreateBlogTagDto[];
  images?: string[];
}
