/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarNoteChecklistItemDto } from '../models/car-note-checklist-item-dto';
export interface CreateCarNoteDto {
  car_id: number;

  /**
   * Palette key; explicit null clears the color.
   */
  color?: string | null;

  /**
   * Defaults to "" — checklist notes have no free-text content.
   */
  content?: string;

  /**
   * Legacy — kept for backward compatibility; prefer `labels`.
   */
  group_name?: string;
  is_checklist?: boolean;
  checked_in_place?: boolean;
  items?: Array<CarNoteChecklistItemDto>;
  labels?: Array<string>;
  title: string;
}
