/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDocumentDto {
  car_id: number;
  document_type: string;
  cnp_id?: string;
  expiry_date?: string;
  file_name?: string;
  file_size?: number;
  file_url?: string;
  issue_date?: string;
  policyholder?: string;
  policy_number?: string;
  provider?: string;
  status?: string;
}
