/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MaintenancePartInputDto } from './maintenance-part-input-dto';

export interface CreateMaintenanceRecordDto {
  car_id: number;
  cost: number;
  description: string;
  expiry_date?: string | null;
  is_diy?: boolean;
  mileage: number;
  parts?: Array<MaintenancePartInputDto>;
  service_category?: 'OIL_CHANGE' | 'BRAKE_SERVICE' | 'TRANSMISSION_SERVICE' | 'TIRE_SERVICE' | 'FLUID_SERVICE' | 'ENGINE_SERVICE' | 'INSPECTION' | 'BATTERY_SERVICE' | 'FILTER_SERVICE' | 'LIGHT_SERVICE' | 'OTHER';
  service_date: string;
  service_type: 'REPAIR' | 'MAINTENANCE' | 'IMPROVEMENT' | 'PASSION';
}
