/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceType } from './maintenance-record-dto';

export interface CreateCarWishDto {
  car_id: number;
  estimated_cost?: number;
  notes?: string;
  service_type?: ServiceType;
  title: string;
}
