/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDocumentDto {
  car_id: number;
  document_type: string;
  expiry_date: string;
  issue_date: string;
}
