/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentDto {
  car_id: number;
  document_type: string;
  id: number;
  cnp_id?: string | null;
  expiry_date?: string | null;
  file_name?: string | null;
  file_size?: number | null;
  file_url?: string | null;
  issue_date?: string | null;
  policyholder?: string | null;
  policy_series?: string | null;
  policy_number?: string | null;
  premium?: number | null;
  currency?: string | null;
  bonus_malus_class?: string | null;
  provider?: string | null;
  status?: string | null;
  is_active: boolean;
}
