/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MaintenancePartDto {
  code?: string | null;
  id: number;
  name: string;
  price?: number | null;
  quantity?: number | null;
}
