/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceCategory } from './maintenance-record-dto';

export interface MaintenanceSettingDto {
  category: ServiceCategory;
  tracked: boolean;
  interval_km: number | null;
  interval_months: number | null;
  is_custom_km: boolean;
  is_custom_months: boolean;
}
