/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MaintenancePartDto } from './maintenance-part-dto';

export type ServiceCategory = 'OIL_CHANGE' | 'BRAKE_SERVICE' | 'TRANSMISSION_SERVICE' | 'TIRE_SERVICE' | 'FLUID_SERVICE' | 'ENGINE_SERVICE' | 'INSPECTION' | 'BATTERY_SERVICE' | 'FILTER_SERVICE' | 'LIGHT_SERVICE' | 'OTHER';
export type ServiceType = 'REPAIR' | 'MAINTENANCE' | 'IMPROVEMENT' | 'PASSION';

export interface MaintenanceRecordDto {
  attachmentsCount: number;
  car_id: number;
  cost: number;
  description: string;
  expiry_date?: string | null;
  id: number;
  is_diy: boolean;
  mileage: number;
  parts: Array<MaintenancePartDto>;
  service_category: ServiceCategory;
  service_date: string;
  service_type: ServiceType;
}
