/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceCategory } from './maintenance-record-dto';

export interface MaintenanceIntervalDto {
  category: ServiceCategory;
  interval_km: number | null;
  interval_months: number | null;
}
