/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarNoteChecklistItemDto } from '../models/car-note-checklist-item-dto';
export interface UpdateCarNoteDto {
  color?: string | null;
  content?: string;
  group_name?: string | null;
  is_checklist?: boolean;
  checked_in_place?: boolean;
  items?: Array<CarNoteChecklistItemDto>;
  labels?: Array<string>;
  title?: string;
}
