/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCarDto {
  id: number;
  make?: string | null;
  model?: string | null;
  variant?: string | null;
  license_plate?: string | null;
  vin?: string | null;
  year?: number | null;
  fuel_type?: 'PETROL' | 'DIESEL' | 'HYBRID' | 'PLUGIN_HYBRID' | 'ELECTRIC' | 'LPG' | null;
  transmission?: 'MANUAL' | 'AUTOMATIC' | 'SEMI_AUTOMATIC' | null;
  engine?: string | null;
  color?: string | null;
  current_mileage?: number | null;
  ownership_start_date?: string | null;
  rca_expiry_date?: string | null;
  itp_expiry_date?: string | null;
  rov_expiry_date?: string | null;
  last_oil_service_date?: string | null;
  last_oil_service_mileage?: number | null;
}
