/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceType } from './maintenance-record-dto';
import { CarWishStatus } from './car-wish-dto';

export interface UpdateCarWishDto {
  estimated_cost?: number | null;
  notes?: string | null;
  service_type?: ServiceType | null;
  status?: CarWishStatus;
  title?: string;
}
