/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarDto } from '../../models/car-dto';
import { UpdateCarDto } from '../../models/update-car-dto';

export interface CarControllerUpdateCar$Params {
  body: UpdateCarDto & {
    files?: File[];
    delete_photo_ids?: number[];
    default_photo_id?: number | null;
    default_new_photo_index?: number | null;
  };
}

export function carControllerUpdateCar(http: HttpClient, rootUrl: string, params: CarControllerUpdateCar$Params, context?: HttpContext): Observable<StrictHttpResponse<CarDto>> {
  const rb = new RequestBuilder(rootUrl, carControllerUpdateCar.PATH, 'put');
  if (params) {
    const { files, delete_photo_ids, default_photo_id, default_new_photo_index, ...carData } = params.body;
    const formData = new FormData();

    Object.entries(carData).forEach(([key, value]) => {
      if (value !== null && value !== undefined) {
        formData.append(key, String(value));
      }
    });

    if (files && files.length > 0) {
      files.forEach(file => formData.append('files', file));
    }

    if (delete_photo_ids && delete_photo_ids.length > 0) {
      formData.append('delete_photo_ids', JSON.stringify(delete_photo_ids));
    }

    if (default_photo_id != null) {
      formData.append('default_photo_id', String(default_photo_id));
    }

    if (default_new_photo_index != null) {
      formData.append('default_new_photo_index', String(default_new_photo_index));
    }

    rb.body(formData);
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<CarDto>)
  );
}

carControllerUpdateCar.PATH = '/api/car';
