/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddCarDto } from '../../models/add-car-dto';
import { CarDto } from '../../models/car-dto';

export interface CarControllerCreateCar$Params {
  body: AddCarDto & { files?: File[] };
}

export function carControllerCreateCar(http: HttpClient, rootUrl: string, params: CarControllerCreateCar$Params, context?: HttpContext): Observable<StrictHttpResponse<CarDto>> {
  const rb = new RequestBuilder(rootUrl, carControllerCreateCar.PATH, 'post');
  if (params) {
    const { files, ...carData } = params.body;
    const formData = new FormData();

    Object.entries(carData).forEach(([key, value]) => {
      if (value !== null && value !== undefined) {
        formData.append(key, String(value));
      }
    });

    if (files && files.length > 0) {
      files.forEach(file => formData.append('files', file));
    }

    rb.body(formData);
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<CarDto>)
  );
}

carControllerCreateCar.PATH = '/api/car';
