/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface CarControllerDeletePhoto$Params {
  photoId: number;
}

export function carControllerDeletePhoto(http: HttpClient, rootUrl: string, params: CarControllerDeletePhoto$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, carControllerDeletePhoto.PATH, 'delete');
  rb.path('photoId', params.photoId);

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<void>)
  );
}

carControllerDeletePhoto.PATH = '/api/car/photo/{photoId}';
