/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { BlogEntryDto } from '../../models/blog-entry-dto';

export interface BlogControllerTogglePin$Params {
  id: string;
}

export function blogControllerTogglePin(
  http: HttpClient,
  rootUrl: string,
  params: BlogControllerTogglePin$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BlogEntryDto>> {
  const rb = new RequestBuilder(rootUrl, blogControllerTogglePin.PATH, 'patch');
  rb.path('id', params.id);
  return http
    .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => r as StrictHttpResponse<BlogEntryDto>),
    );
}

blogControllerTogglePin.PATH = '/api/blog/{id}/pin';
