/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { BlogEntryDto } from '../../models/blog-entry-dto';
import { CreateBlogEntryDto } from '../../models/create-blog-entry-dto';

export interface BlogControllerCreateEntry$Params {
  body: CreateBlogEntryDto;
}

export function blogControllerCreateEntry(
  http: HttpClient,
  rootUrl: string,
  params: BlogControllerCreateEntry$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BlogEntryDto>> {
  const rb = new RequestBuilder(rootUrl, blogControllerCreateEntry.PATH, 'post');
  rb.body(params.body, 'application/json');
  return http
    .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => r as StrictHttpResponse<BlogEntryDto>),
    );
}

blogControllerCreateEntry.PATH = '/api/blog';
