/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { BlogEntryDto } from '../../models/blog-entry-dto';
import { UpdateBlogEntryDto } from '../../models/update-blog-entry-dto';

export interface BlogControllerUpdateEntry$Params {
  id: string;
  body: UpdateBlogEntryDto;
}

export function blogControllerUpdateEntry(
  http: HttpClient,
  rootUrl: string,
  params: BlogControllerUpdateEntry$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BlogEntryDto>> {
  const rb = new RequestBuilder(rootUrl, blogControllerUpdateEntry.PATH, 'put');
  rb.path('id', params.id);
  rb.body(params.body, 'application/json');
  return http
    .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => r as StrictHttpResponse<BlogEntryDto>),
    );
}

blogControllerUpdateEntry.PATH = '/api/blog/{id}';
