/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { BlogEntryDto, BlogCategoryApi, VehicleEntryCategoryApi } from '../../models/blog-entry-dto';

export interface BlogControllerGetEntries$Params {
  category?: BlogCategoryApi;
  car_id?: number;
  vehicle_category?: VehicleEntryCategoryApi;
  search?: string;
  is_pinned?: boolean;
}

export function blogControllerGetEntries(
  http: HttpClient,
  rootUrl: string,
  params?: BlogControllerGetEntries$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BlogEntryDto[]>> {
  const rb = new RequestBuilder(rootUrl, blogControllerGetEntries.PATH, 'get');
  if (params) {
    if (params.category         != null) rb.query('category',          params.category);
    if (params.car_id           != null) rb.query('car_id',            params.car_id);
    if (params.vehicle_category != null) rb.query('vehicle_category',  params.vehicle_category);
    if (params.search           != null) rb.query('search',            params.search);
    if (params.is_pinned        != null) rb.query('is_pinned',         params.is_pinned);
  }
  return http
    .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => r as StrictHttpResponse<BlogEntryDto[]>),
    );
}

blogControllerGetEntries.PATH = '/api/blog';
