/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { MakeResponseDto } from '../../models/make-response-dto';

export interface VehicleCatalogControllerGetMakes$Params {}

export function vehicleCatalogControllerGetMakes(
  http: HttpClient,
  rootUrl: string,
  params?: VehicleCatalogControllerGetMakes$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<MakeResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, vehicleCatalogControllerGetMakes.PATH, 'get');

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context }),
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<Array<MakeResponseDto>>),
  );
}

vehicleCatalogControllerGetMakes.PATH = '/api/vehicle-catalog/makes';
