/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { YearResponseDto } from '../../models/year-response-dto';

export interface VehicleCatalogControllerGetYears$Params {
  modelId: number;
}

export function vehicleCatalogControllerGetYears(
  http: HttpClient,
  rootUrl: string,
  params: VehicleCatalogControllerGetYears$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<YearResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, vehicleCatalogControllerGetYears.PATH, 'get');
  rb.path('modelId', params.modelId, {});

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context }),
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<Array<YearResponseDto>>),
  );
}

vehicleCatalogControllerGetYears.PATH = '/api/vehicle-catalog/models/{modelId}/years';
