/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { ModelResponseDto } from '../../models/model-response-dto';

export interface VehicleCatalogControllerGetModels$Params {
  makeId: number;
}

export function vehicleCatalogControllerGetModels(
  http: HttpClient,
  rootUrl: string,
  params: VehicleCatalogControllerGetModels$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<ModelResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, vehicleCatalogControllerGetModels.PATH, 'get');
  rb.path('makeId', params.makeId, {});

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context }),
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<Array<ModelResponseDto>>),
  );
}

vehicleCatalogControllerGetModels.PATH = '/api/vehicle-catalog/makes/{makeId}/models';
