/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AddCarDto } from './models/add-car-dto';
export type { CarDto, CarPhotoDto } from './models/car-dto';
export type { CreateDocumentDto } from './models/create-document-dto';
export type { CreateMaintenanceRecordDto } from './models/create-maintenance-record-dto';
export type { DocumentDto } from './models/document-dto';
export type { MaintenanceRecordDto } from './models/maintenance-record-dto';
export type { UpdateCarDto } from './models/update-car-dto';
export type { UpdateDocumentDto } from './models/update-document-dto';
export type { UpdateMaintenanceRecordDto } from './models/update-maintenance-record-dto';
